name: Client Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            script: ./test_environment.sh
            lock: zwik_environment_linux-64.lock
          - os: macos-latest
            script: ./test_environment.sh
            lock: zwik_environment_osx-64.lock
          - os: windows-latest
            script: .\test_environment.bat --unattended
            lock: zwik_environment_win-64.lock
    steps:
      - uses: actions/checkout@v4
      - name: Run unittests
        run: |
          ${{ matrix.script }} -v --update-all --exec python tasks.py unittest
      - name: Check update mechanism
        run: |
          ${{ matrix.script }} -v --check-installation --fix
          ${{ matrix.script }} -v --version
      - name: Print updated lock file
        run: |
          cat .zwik/${{ matrix.lock }}
